/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as SponsorRouteImport } from './routes/_sponsor'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentDiscoverRouteImport } from './routes/_student/discover'
import { Route as SponsorScholarshipsRouteImport } from './routes/_sponsor/scholarships'
import { Route as OnboardingWelcomeRouteImport } from './routes/_onboarding/welcome'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/_onboarding/role-selection'
import { Route as OnboardingProfileSetupRouteImport } from './routes/_onboarding/profile-setup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthTermsConditionsRouteImport } from './routes/_auth/terms-conditions'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthResendRouteImport } from './routes/_auth/resend'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthPrivacyPolicyRouteImport } from './routes/_auth/privacy-policy'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthEmailVerificationSentRouteImport } from './routes/_auth/email-verification-sent'
import { Route as AuthConfirmationRouteImport } from './routes/_auth/confirmation'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as StudentHomeIndexRouteImport } from './routes/_student/home/index'
import { Route as SponsorCreateIndexRouteImport } from './routes/_sponsor/create/index'
import { Route as LandingAboutIndexRouteImport } from './routes/_landing/about/index'
import { Route as StudentScholarshipIdApplyRouteImport } from './routes/_student/scholarship/$id/apply'
import { Route as SponsorScholarshipIdApplicantsRouteImport } from './routes/_sponsor/scholarship/$id/applicants'
import { Route as StudentProfileStudentStudentIdIndexRouteImport } from './routes/_student/profile/student/$studentId/index'
import { Route as SponsorScholarshipIdEditIndexRouteImport } from './routes/_sponsor/scholarship/$id/edit/index'
import { Route as SponsorProfileSponsorSponsorIdIndexRouteImport } from './routes/_sponsor/profile/sponsor/$sponsorId/index'

const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/_sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDiscoverRoute = StudentDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => StudentRoute,
} as any)
const SponsorScholarshipsRoute = SponsorScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => SponsorRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileSetupRoute = OnboardingProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTermsConditionsRoute = AuthTermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResendRoute = AuthResendRouteImport.update({
  id: '/resend',
  path: '/resend',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPrivacyPolicyRoute = AuthPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationSentRoute =
  AuthEmailVerificationSentRouteImport.update({
    id: '/email-verification-sent',
    path: '/email-verification-sent',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConfirmationRoute = AuthConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const StudentHomeIndexRoute = StudentHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => StudentRoute,
} as any)
const SponsorCreateIndexRoute = SponsorCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => SponsorRoute,
} as any)
const LandingAboutIndexRoute = LandingAboutIndexRouteImport.update({
  id: '/_landing/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScholarshipIdApplyRoute =
  StudentScholarshipIdApplyRouteImport.update({
    id: '/scholarship/$id/apply',
    path: '/scholarship/$id/apply',
    getParentRoute: () => StudentRoute,
  } as any)
const SponsorScholarshipIdApplicantsRoute =
  SponsorScholarshipIdApplicantsRouteImport.update({
    id: '/scholarship/$id/applicants',
    path: '/scholarship/$id/applicants',
    getParentRoute: () => SponsorRoute,
  } as any)
const StudentProfileStudentStudentIdIndexRoute =
  StudentProfileStudentStudentIdIndexRouteImport.update({
    id: '/profile/student/$studentId/',
    path: '/profile/student/$studentId/',
    getParentRoute: () => StudentRoute,
  } as any)
const SponsorScholarshipIdEditIndexRoute =
  SponsorScholarshipIdEditIndexRouteImport.update({
    id: '/scholarship/$id/edit/',
    path: '/scholarship/$id/edit/',
    getParentRoute: () => SponsorRoute,
  } as any)
const SponsorProfileSponsorSponsorIdIndexRoute =
  SponsorProfileSponsorSponsorIdIndexRouteImport.update({
    id: '/profile/sponsor/$sponsorId/',
    path: '/profile/sponsor/$sponsorId/',
    getParentRoute: () => SponsorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users': typeof AdminUsersRoute
  '/confirmation': typeof AuthConfirmationRoute
  '/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/register': typeof AuthRegisterRoute
  '/resend': typeof AuthResendRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms-conditions': typeof AuthTermsConditionsRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/about': typeof LandingAboutIndexRoute
  '/create': typeof SponsorCreateIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditIndexRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users': typeof AdminUsersRoute
  '/confirmation': typeof AuthConfirmationRoute
  '/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/register': typeof AuthRegisterRoute
  '/resend': typeof AuthResendRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/terms-conditions': typeof AuthTermsConditionsRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/about': typeof LandingAboutIndexRoute
  '/create': typeof SponsorCreateIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditIndexRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_sponsor': typeof SponsorRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_auth/confirmation': typeof AuthConfirmationRoute
  '/_auth/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/resend': typeof AuthResendRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/terms-conditions': typeof AuthTermsConditionsRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_onboarding/profile-setup': typeof OnboardingProfileSetupRoute
  '/_onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/_onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_sponsor/scholarships': typeof SponsorScholarshipsRoute
  '/_student/discover': typeof StudentDiscoverRoute
  '/_landing/about/': typeof LandingAboutIndexRoute
  '/_sponsor/create/': typeof SponsorCreateIndexRoute
  '/_student/home/': typeof StudentHomeIndexRoute
  '/_sponsor/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/_student/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
  '/_sponsor/profile/sponsor/$sponsorId/': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/_sponsor/scholarship/$id/edit/': typeof SponsorScholarshipIdEditIndexRoute
  '/_student/profile/student/$studentId/': typeof StudentProfileStudentStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/users'
    | '/confirmation'
    | '/email-verification-sent'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/resend'
    | '/reset-password'
    | '/terms-conditions'
    | '/verify'
    | '/verify-email'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/scholarships'
    | '/discover'
    | '/about'
    | '/create'
    | '/home'
    | '/scholarship/$id/applicants'
    | '/scholarship/$id/apply'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/users'
    | '/confirmation'
    | '/email-verification-sent'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/resend'
    | '/reset-password'
    | '/terms-conditions'
    | '/verify'
    | '/verify-email'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/scholarships'
    | '/discover'
    | '/about'
    | '/create'
    | '/home'
    | '/scholarship/$id/applicants'
    | '/scholarship/$id/apply'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_onboarding'
    | '/_sponsor'
    | '/_student'
    | '/_admin/dashboard'
    | '/_admin/users'
    | '/_auth/confirmation'
    | '/_auth/email-verification-sent'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/privacy-policy'
    | '/_auth/register'
    | '/_auth/resend'
    | '/_auth/reset-password'
    | '/_auth/terms-conditions'
    | '/_auth/verify'
    | '/_auth/verify-email'
    | '/_onboarding/profile-setup'
    | '/_onboarding/role-selection'
    | '/_onboarding/welcome'
    | '/_sponsor/scholarships'
    | '/_student/discover'
    | '/_landing/about/'
    | '/_sponsor/create/'
    | '/_student/home/'
    | '/_sponsor/scholarship/$id/applicants'
    | '/_student/scholarship/$id/apply'
    | '/_sponsor/profile/sponsor/$sponsorId/'
    | '/_sponsor/scholarship/$id/edit/'
    | '/_student/profile/student/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SponsorRoute: typeof SponsorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  LandingAboutIndexRoute: typeof LandingAboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sponsor': {
      id: '/_sponsor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/discover': {
      id: '/_student/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof StudentDiscoverRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarships': {
      id: '/_sponsor/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof SponsorScholarshipsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_onboarding/welcome': {
      id: '/_onboarding/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-selection': {
      id: '/_onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/profile-setup': {
      id: '/_onboarding/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof OnboardingProfileSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/terms-conditions': {
      id: '/_auth/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof AuthTermsConditionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resend': {
      id: '/_auth/resend'
      path: '/resend'
      fullPath: '/resend'
      preLoaderRoute: typeof AuthResendRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/privacy-policy': {
      id: '/_auth/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AuthPrivacyPolicyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email-verification-sent': {
      id: '/_auth/email-verification-sent'
      path: '/email-verification-sent'
      fullPath: '/email-verification-sent'
      preLoaderRoute: typeof AuthEmailVerificationSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirmation': {
      id: '/_auth/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof AuthConfirmationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/home/': {
      id: '/_student/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof StudentHomeIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/create/': {
      id: '/_sponsor/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof SponsorCreateIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_landing/about/': {
      id: '/_landing/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/scholarship/$id/apply': {
      id: '/_student/scholarship/$id/apply'
      path: '/scholarship/$id/apply'
      fullPath: '/scholarship/$id/apply'
      preLoaderRoute: typeof StudentScholarshipIdApplyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarship/$id/applicants': {
      id: '/_sponsor/scholarship/$id/applicants'
      path: '/scholarship/$id/applicants'
      fullPath: '/scholarship/$id/applicants'
      preLoaderRoute: typeof SponsorScholarshipIdApplicantsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_student/profile/student/$studentId/': {
      id: '/_student/profile/student/$studentId/'
      path: '/profile/student/$studentId'
      fullPath: '/profile/student/$studentId'
      preLoaderRoute: typeof StudentProfileStudentStudentIdIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarship/$id/edit/': {
      id: '/_sponsor/scholarship/$id/edit/'
      path: '/scholarship/$id/edit'
      fullPath: '/scholarship/$id/edit'
      preLoaderRoute: typeof SponsorScholarshipIdEditIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/profile/sponsor/$sponsorId/': {
      id: '/_sponsor/profile/sponsor/$sponsorId/'
      path: '/profile/sponsor/$sponsorId'
      fullPath: '/profile/sponsor/$sponsorId'
      preLoaderRoute: typeof SponsorProfileSponsorSponsorIdIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthConfirmationRoute: typeof AuthConfirmationRoute
  AuthEmailVerificationSentRoute: typeof AuthEmailVerificationSentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPrivacyPolicyRoute: typeof AuthPrivacyPolicyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResendRoute: typeof AuthResendRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTermsConditionsRoute: typeof AuthTermsConditionsRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmationRoute: AuthConfirmationRoute,
  AuthEmailVerificationSentRoute: AuthEmailVerificationSentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPrivacyPolicyRoute: AuthPrivacyPolicyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResendRoute: AuthResendRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTermsConditionsRoute: AuthTermsConditionsRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingProfileSetupRoute: typeof OnboardingProfileSetupRoute
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProfileSetupRoute: OnboardingProfileSetupRoute,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SponsorRouteChildren {
  SponsorScholarshipsRoute: typeof SponsorScholarshipsRoute
  SponsorCreateIndexRoute: typeof SponsorCreateIndexRoute
  SponsorScholarshipIdApplicantsRoute: typeof SponsorScholarshipIdApplicantsRoute
  SponsorProfileSponsorSponsorIdIndexRoute: typeof SponsorProfileSponsorSponsorIdIndexRoute
  SponsorScholarshipIdEditIndexRoute: typeof SponsorScholarshipIdEditIndexRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorScholarshipsRoute: SponsorScholarshipsRoute,
  SponsorCreateIndexRoute: SponsorCreateIndexRoute,
  SponsorScholarshipIdApplicantsRoute: SponsorScholarshipIdApplicantsRoute,
  SponsorProfileSponsorSponsorIdIndexRoute:
    SponsorProfileSponsorSponsorIdIndexRoute,
  SponsorScholarshipIdEditIndexRoute: SponsorScholarshipIdEditIndexRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

interface StudentRouteChildren {
  StudentDiscoverRoute: typeof StudentDiscoverRoute
  StudentHomeIndexRoute: typeof StudentHomeIndexRoute
  StudentScholarshipIdApplyRoute: typeof StudentScholarshipIdApplyRoute
  StudentProfileStudentStudentIdIndexRoute: typeof StudentProfileStudentStudentIdIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDiscoverRoute: StudentDiscoverRoute,
  StudentHomeIndexRoute: StudentHomeIndexRoute,
  StudentScholarshipIdApplyRoute: StudentScholarshipIdApplyRoute,
  StudentProfileStudentStudentIdIndexRoute:
    StudentProfileStudentStudentIdIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SponsorRoute: SponsorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LandingAboutIndexRoute: LandingAboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
