/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as SponsorRouteImport } from './routes/_sponsor'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as _404RouteImport } from './routes/__404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationCallbackRouteImport } from './routes/verification/callback'
import { Route as OnboardingWelcomeRouteImport } from './routes/_onboarding/welcome'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/_onboarding/role-selection'
import { Route as OnboardingProfileSetupRouteImport } from './routes/_onboarding/profile-setup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthResendRouteImport } from './routes/_auth/resend'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthEmailVerificationSentRouteImport } from './routes/_auth/email-verification-sent'
import { Route as AuthConfirmationRouteImport } from './routes/_auth/confirmation'
import { Route as AdminUsersManagementRouteImport } from './routes/_admin/users-management'
import { Route as AdminScholarshipsManagementRouteImport } from './routes/_admin/scholarships-management'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as StudentHomeIndexRouteImport } from './routes/_student/home/index'
import { Route as StudentDiscoverIndexRouteImport } from './routes/_student/discover/index'
import { Route as StudentDisbursementsIndexRouteImport } from './routes/_student/disbursements/index'
import { Route as SponsorScholarshipsIndexRouteImport } from './routes/_sponsor/scholarships/index'
import { Route as SponsorScholarsIndexRouteImport } from './routes/_sponsor/scholars/index'
import { Route as SponsorCreateIndexRouteImport } from './routes/_sponsor/create/index'
import { Route as OnboardingProfileSetupIndexRouteImport } from './routes/_onboarding/profile-setup/index'
import { Route as LandingAboutIndexRouteImport } from './routes/_landing/about/index'
import { Route as OnboardingProfileSetupStudentRouteImport } from './routes/_onboarding/profile-setup/student'
import { Route as OnboardingProfileSetupSchoolRouteImport } from './routes/_onboarding/profile-setup/school'
import { Route as OnboardingProfileSetupOrganizationSponsorRouteImport } from './routes/_onboarding/profile-setup/organization-sponsor'
import { Route as OnboardingProfileSetupIndividualSponsorRouteImport } from './routes/_onboarding/profile-setup/individual-sponsor'
import { Route as OnboardingProfileSetupGovernmentSponsorRouteImport } from './routes/_onboarding/profile-setup/government-sponsor'
import { Route as SponsorScholarshipIdApplicantsRouteImport } from './routes/_sponsor/scholarship/$id/applicants'
import { Route as StudentScholarshipIdApplyIndexRouteImport } from './routes/_student/scholarship/$id/apply/index'
import { Route as StudentProfileStudentStudentIdIndexRouteImport } from './routes/_student/profile/student/$studentId/index'
import { Route as SponsorScholarshipIdEditIndexRouteImport } from './routes/_sponsor/scholarship/$id/edit/index'
import { Route as SponsorProfileSponsorSponsorIdIndexRouteImport } from './routes/_sponsor/profile/sponsor/$sponsorId/index'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/_sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _404Route = _404RouteImport.update({
  id: '/__404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationCallbackRoute = VerificationCallbackRouteImport.update({
  id: '/verification/callback',
  path: '/verification/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileSetupRoute = OnboardingProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResendRoute = AuthResendRouteImport.update({
  id: '/resend',
  path: '/resend',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationSentRoute =
  AuthEmailVerificationSentRouteImport.update({
    id: '/email-verification-sent',
    path: '/email-verification-sent',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConfirmationRoute = AuthConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersManagementRoute = AdminUsersManagementRouteImport.update({
  id: '/users-management',
  path: '/users-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScholarshipsManagementRoute =
  AdminScholarshipsManagementRouteImport.update({
    id: '/scholarships-management',
    path: '/scholarships-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const StudentHomeIndexRoute = StudentHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDiscoverIndexRoute = StudentDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDisbursementsIndexRoute =
  StudentDisbursementsIndexRouteImport.update({
    id: '/disbursements/',
    path: '/disbursements/',
    getParentRoute: () => StudentRoute,
  } as any)
const SponsorScholarshipsIndexRoute =
  SponsorScholarshipsIndexRouteImport.update({
    id: '/scholarships/',
    path: '/scholarships/',
    getParentRoute: () => SponsorRoute,
  } as any)
const SponsorScholarsIndexRoute = SponsorScholarsIndexRouteImport.update({
  id: '/scholars/',
  path: '/scholars/',
  getParentRoute: () => SponsorRoute,
} as any)
const SponsorCreateIndexRoute = SponsorCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => SponsorRoute,
} as any)
const OnboardingProfileSetupIndexRoute =
  OnboardingProfileSetupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const LandingAboutIndexRoute = LandingAboutIndexRouteImport.update({
  id: '/_landing/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileSetupStudentRoute =
  OnboardingProfileSetupStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const OnboardingProfileSetupSchoolRoute =
  OnboardingProfileSetupSchoolRouteImport.update({
    id: '/school',
    path: '/school',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const OnboardingProfileSetupOrganizationSponsorRoute =
  OnboardingProfileSetupOrganizationSponsorRouteImport.update({
    id: '/organization-sponsor',
    path: '/organization-sponsor',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const OnboardingProfileSetupIndividualSponsorRoute =
  OnboardingProfileSetupIndividualSponsorRouteImport.update({
    id: '/individual-sponsor',
    path: '/individual-sponsor',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const OnboardingProfileSetupGovernmentSponsorRoute =
  OnboardingProfileSetupGovernmentSponsorRouteImport.update({
    id: '/government-sponsor',
    path: '/government-sponsor',
    getParentRoute: () => OnboardingProfileSetupRoute,
  } as any)
const SponsorScholarshipIdApplicantsRoute =
  SponsorScholarshipIdApplicantsRouteImport.update({
    id: '/scholarship/$id/applicants',
    path: '/scholarship/$id/applicants',
    getParentRoute: () => SponsorRoute,
  } as any)
const StudentScholarshipIdApplyIndexRoute =
  StudentScholarshipIdApplyIndexRouteImport.update({
    id: '/scholarship/$id/apply/',
    path: '/scholarship/$id/apply/',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentProfileStudentStudentIdIndexRoute =
  StudentProfileStudentStudentIdIndexRouteImport.update({
    id: '/profile/student/$studentId/',
    path: '/profile/student/$studentId/',
    getParentRoute: () => StudentRoute,
  } as any)
const SponsorScholarshipIdEditIndexRoute =
  SponsorScholarshipIdEditIndexRouteImport.update({
    id: '/scholarship/$id/edit/',
    path: '/scholarship/$id/edit/',
    getParentRoute: () => SponsorRoute,
  } as any)
const SponsorProfileSponsorSponsorIdIndexRoute =
  SponsorProfileSponsorSponsorIdIndexRouteImport.update({
    id: '/profile/sponsor/$sponsorId/',
    path: '/profile/sponsor/$sponsorId/',
    getParentRoute: () => SponsorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/scholarships-management': typeof AdminScholarshipsManagementRoute
  '/users-management': typeof AdminUsersManagementRoute
  '/confirmation': typeof AuthConfirmationRoute
  '/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/resend': typeof AuthResendRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/profile-setup': typeof OnboardingProfileSetupRouteWithChildren
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/verification/callback': typeof VerificationCallbackRoute
  '/profile-setup/government-sponsor': typeof OnboardingProfileSetupGovernmentSponsorRoute
  '/profile-setup/individual-sponsor': typeof OnboardingProfileSetupIndividualSponsorRoute
  '/profile-setup/organization-sponsor': typeof OnboardingProfileSetupOrganizationSponsorRoute
  '/profile-setup/school': typeof OnboardingProfileSetupSchoolRoute
  '/profile-setup/student': typeof OnboardingProfileSetupStudentRoute
  '/about': typeof LandingAboutIndexRoute
  '/profile-setup/': typeof OnboardingProfileSetupIndexRoute
  '/create': typeof SponsorCreateIndexRoute
  '/scholars': typeof SponsorScholarsIndexRoute
  '/scholarships': typeof SponsorScholarshipsIndexRoute
  '/disbursements': typeof StudentDisbursementsIndexRoute
  '/discover': typeof StudentDiscoverIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditIndexRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdIndexRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/scholarships-management': typeof AdminScholarshipsManagementRoute
  '/users-management': typeof AdminUsersManagementRoute
  '/confirmation': typeof AuthConfirmationRoute
  '/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/resend': typeof AuthResendRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/verification/callback': typeof VerificationCallbackRoute
  '/profile-setup/government-sponsor': typeof OnboardingProfileSetupGovernmentSponsorRoute
  '/profile-setup/individual-sponsor': typeof OnboardingProfileSetupIndividualSponsorRoute
  '/profile-setup/organization-sponsor': typeof OnboardingProfileSetupOrganizationSponsorRoute
  '/profile-setup/school': typeof OnboardingProfileSetupSchoolRoute
  '/profile-setup/student': typeof OnboardingProfileSetupStudentRoute
  '/about': typeof LandingAboutIndexRoute
  '/profile-setup': typeof OnboardingProfileSetupIndexRoute
  '/create': typeof SponsorCreateIndexRoute
  '/scholars': typeof SponsorScholarsIndexRoute
  '/scholarships': typeof SponsorScholarshipsIndexRoute
  '/disbursements': typeof StudentDisbursementsIndexRoute
  '/discover': typeof StudentDiscoverIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditIndexRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdIndexRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__404': typeof _404Route
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_sponsor': typeof SponsorRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/scholarships-management': typeof AdminScholarshipsManagementRoute
  '/_admin/users-management': typeof AdminUsersManagementRoute
  '/_auth/confirmation': typeof AuthConfirmationRoute
  '/_auth/email-verification-sent': typeof AuthEmailVerificationSentRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/resend': typeof AuthResendRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_onboarding/profile-setup': typeof OnboardingProfileSetupRouteWithChildren
  '/_onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/_onboarding/welcome': typeof OnboardingWelcomeRoute
  '/verification/callback': typeof VerificationCallbackRoute
  '/_onboarding/profile-setup/government-sponsor': typeof OnboardingProfileSetupGovernmentSponsorRoute
  '/_onboarding/profile-setup/individual-sponsor': typeof OnboardingProfileSetupIndividualSponsorRoute
  '/_onboarding/profile-setup/organization-sponsor': typeof OnboardingProfileSetupOrganizationSponsorRoute
  '/_onboarding/profile-setup/school': typeof OnboardingProfileSetupSchoolRoute
  '/_onboarding/profile-setup/student': typeof OnboardingProfileSetupStudentRoute
  '/_landing/about/': typeof LandingAboutIndexRoute
  '/_onboarding/profile-setup/': typeof OnboardingProfileSetupIndexRoute
  '/_sponsor/create/': typeof SponsorCreateIndexRoute
  '/_sponsor/scholars/': typeof SponsorScholarsIndexRoute
  '/_sponsor/scholarships/': typeof SponsorScholarshipsIndexRoute
  '/_student/disbursements/': typeof StudentDisbursementsIndexRoute
  '/_student/discover/': typeof StudentDiscoverIndexRoute
  '/_student/home/': typeof StudentHomeIndexRoute
  '/_sponsor/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/_sponsor/profile/sponsor/$sponsorId/': typeof SponsorProfileSponsorSponsorIdIndexRoute
  '/_sponsor/scholarship/$id/edit/': typeof SponsorScholarshipIdEditIndexRoute
  '/_student/profile/student/$studentId/': typeof StudentProfileStudentStudentIdIndexRoute
  '/_student/scholarship/$id/apply/': typeof StudentScholarshipIdApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/dashboard'
    | '/scholarships-management'
    | '/users-management'
    | '/confirmation'
    | '/email-verification-sent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/resend'
    | '/reset-password'
    | '/verify'
    | '/verify-email'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/verification/callback'
    | '/profile-setup/government-sponsor'
    | '/profile-setup/individual-sponsor'
    | '/profile-setup/organization-sponsor'
    | '/profile-setup/school'
    | '/profile-setup/student'
    | '/about'
    | '/profile-setup/'
    | '/create'
    | '/scholars'
    | '/scholarships'
    | '/disbursements'
    | '/discover'
    | '/home'
    | '/scholarship/$id/applicants'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
    | '/scholarship/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/dashboard'
    | '/scholarships-management'
    | '/users-management'
    | '/confirmation'
    | '/email-verification-sent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/resend'
    | '/reset-password'
    | '/verify'
    | '/verify-email'
    | '/role-selection'
    | '/welcome'
    | '/verification/callback'
    | '/profile-setup/government-sponsor'
    | '/profile-setup/individual-sponsor'
    | '/profile-setup/organization-sponsor'
    | '/profile-setup/school'
    | '/profile-setup/student'
    | '/about'
    | '/profile-setup'
    | '/create'
    | '/scholars'
    | '/scholarships'
    | '/disbursements'
    | '/discover'
    | '/home'
    | '/scholarship/$id/applicants'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
    | '/scholarship/$id/apply'
  id:
    | '__root__'
    | '/'
    | '/__404'
    | '/_admin'
    | '/_auth'
    | '/_onboarding'
    | '/_sponsor'
    | '/_student'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/_admin/dashboard'
    | '/_admin/scholarships-management'
    | '/_admin/users-management'
    | '/_auth/confirmation'
    | '/_auth/email-verification-sent'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/resend'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/_auth/verify-email'
    | '/_onboarding/profile-setup'
    | '/_onboarding/role-selection'
    | '/_onboarding/welcome'
    | '/verification/callback'
    | '/_onboarding/profile-setup/government-sponsor'
    | '/_onboarding/profile-setup/individual-sponsor'
    | '/_onboarding/profile-setup/organization-sponsor'
    | '/_onboarding/profile-setup/school'
    | '/_onboarding/profile-setup/student'
    | '/_landing/about/'
    | '/_onboarding/profile-setup/'
    | '/_sponsor/create/'
    | '/_sponsor/scholars/'
    | '/_sponsor/scholarships/'
    | '/_student/disbursements/'
    | '/_student/discover/'
    | '/_student/home/'
    | '/_sponsor/scholarship/$id/applicants'
    | '/_sponsor/profile/sponsor/$sponsorId/'
    | '/_sponsor/scholarship/$id/edit/'
    | '/_student/profile/student/$studentId/'
    | '/_student/scholarship/$id/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _404Route: typeof _404Route
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SponsorRoute: typeof SponsorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  VerificationCallbackRoute: typeof VerificationCallbackRoute
  LandingAboutIndexRoute: typeof LandingAboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sponsor': {
      id: '/_sponsor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__404': {
      id: '/__404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/callback': {
      id: '/verification/callback'
      path: '/verification/callback'
      fullPath: '/verification/callback'
      preLoaderRoute: typeof VerificationCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/welcome': {
      id: '/_onboarding/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-selection': {
      id: '/_onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/profile-setup': {
      id: '/_onboarding/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof OnboardingProfileSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resend': {
      id: '/_auth/resend'
      path: '/resend'
      fullPath: '/resend'
      preLoaderRoute: typeof AuthResendRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email-verification-sent': {
      id: '/_auth/email-verification-sent'
      path: '/email-verification-sent'
      fullPath: '/email-verification-sent'
      preLoaderRoute: typeof AuthEmailVerificationSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirmation': {
      id: '/_auth/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof AuthConfirmationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/users-management': {
      id: '/_admin/users-management'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AdminUsersManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/scholarships-management': {
      id: '/_admin/scholarships-management'
      path: '/scholarships-management'
      fullPath: '/scholarships-management'
      preLoaderRoute: typeof AdminScholarshipsManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/home/': {
      id: '/_student/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof StudentHomeIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/discover/': {
      id: '/_student/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof StudentDiscoverIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/disbursements/': {
      id: '/_student/disbursements/'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof StudentDisbursementsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarships/': {
      id: '/_sponsor/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof SponsorScholarshipsIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/scholars/': {
      id: '/_sponsor/scholars/'
      path: '/scholars'
      fullPath: '/scholars'
      preLoaderRoute: typeof SponsorScholarsIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/create/': {
      id: '/_sponsor/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof SponsorCreateIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_onboarding/profile-setup/': {
      id: '/_onboarding/profile-setup/'
      path: '/'
      fullPath: '/profile-setup/'
      preLoaderRoute: typeof OnboardingProfileSetupIndexRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_landing/about/': {
      id: '/_landing/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/profile-setup/student': {
      id: '/_onboarding/profile-setup/student'
      path: '/student'
      fullPath: '/profile-setup/student'
      preLoaderRoute: typeof OnboardingProfileSetupStudentRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_onboarding/profile-setup/school': {
      id: '/_onboarding/profile-setup/school'
      path: '/school'
      fullPath: '/profile-setup/school'
      preLoaderRoute: typeof OnboardingProfileSetupSchoolRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_onboarding/profile-setup/organization-sponsor': {
      id: '/_onboarding/profile-setup/organization-sponsor'
      path: '/organization-sponsor'
      fullPath: '/profile-setup/organization-sponsor'
      preLoaderRoute: typeof OnboardingProfileSetupOrganizationSponsorRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_onboarding/profile-setup/individual-sponsor': {
      id: '/_onboarding/profile-setup/individual-sponsor'
      path: '/individual-sponsor'
      fullPath: '/profile-setup/individual-sponsor'
      preLoaderRoute: typeof OnboardingProfileSetupIndividualSponsorRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_onboarding/profile-setup/government-sponsor': {
      id: '/_onboarding/profile-setup/government-sponsor'
      path: '/government-sponsor'
      fullPath: '/profile-setup/government-sponsor'
      preLoaderRoute: typeof OnboardingProfileSetupGovernmentSponsorRouteImport
      parentRoute: typeof OnboardingProfileSetupRoute
    }
    '/_sponsor/scholarship/$id/applicants': {
      id: '/_sponsor/scholarship/$id/applicants'
      path: '/scholarship/$id/applicants'
      fullPath: '/scholarship/$id/applicants'
      preLoaderRoute: typeof SponsorScholarshipIdApplicantsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_student/scholarship/$id/apply/': {
      id: '/_student/scholarship/$id/apply/'
      path: '/scholarship/$id/apply'
      fullPath: '/scholarship/$id/apply'
      preLoaderRoute: typeof StudentScholarshipIdApplyIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile/student/$studentId/': {
      id: '/_student/profile/student/$studentId/'
      path: '/profile/student/$studentId'
      fullPath: '/profile/student/$studentId'
      preLoaderRoute: typeof StudentProfileStudentStudentIdIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarship/$id/edit/': {
      id: '/_sponsor/scholarship/$id/edit/'
      path: '/scholarship/$id/edit'
      fullPath: '/scholarship/$id/edit'
      preLoaderRoute: typeof SponsorScholarshipIdEditIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/profile/sponsor/$sponsorId/': {
      id: '/_sponsor/profile/sponsor/$sponsorId/'
      path: '/profile/sponsor/$sponsorId'
      fullPath: '/profile/sponsor/$sponsorId'
      preLoaderRoute: typeof SponsorProfileSponsorSponsorIdIndexRouteImport
      parentRoute: typeof SponsorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminScholarshipsManagementRoute: typeof AdminScholarshipsManagementRoute
  AdminUsersManagementRoute: typeof AdminUsersManagementRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminScholarshipsManagementRoute: AdminScholarshipsManagementRoute,
  AdminUsersManagementRoute: AdminUsersManagementRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthConfirmationRoute: typeof AuthConfirmationRoute
  AuthEmailVerificationSentRoute: typeof AuthEmailVerificationSentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResendRoute: typeof AuthResendRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmationRoute: AuthConfirmationRoute,
  AuthEmailVerificationSentRoute: AuthEmailVerificationSentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResendRoute: AuthResendRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingProfileSetupRouteChildren {
  OnboardingProfileSetupGovernmentSponsorRoute: typeof OnboardingProfileSetupGovernmentSponsorRoute
  OnboardingProfileSetupIndividualSponsorRoute: typeof OnboardingProfileSetupIndividualSponsorRoute
  OnboardingProfileSetupOrganizationSponsorRoute: typeof OnboardingProfileSetupOrganizationSponsorRoute
  OnboardingProfileSetupSchoolRoute: typeof OnboardingProfileSetupSchoolRoute
  OnboardingProfileSetupStudentRoute: typeof OnboardingProfileSetupStudentRoute
  OnboardingProfileSetupIndexRoute: typeof OnboardingProfileSetupIndexRoute
}

const OnboardingProfileSetupRouteChildren: OnboardingProfileSetupRouteChildren =
  {
    OnboardingProfileSetupGovernmentSponsorRoute:
      OnboardingProfileSetupGovernmentSponsorRoute,
    OnboardingProfileSetupIndividualSponsorRoute:
      OnboardingProfileSetupIndividualSponsorRoute,
    OnboardingProfileSetupOrganizationSponsorRoute:
      OnboardingProfileSetupOrganizationSponsorRoute,
    OnboardingProfileSetupSchoolRoute: OnboardingProfileSetupSchoolRoute,
    OnboardingProfileSetupStudentRoute: OnboardingProfileSetupStudentRoute,
    OnboardingProfileSetupIndexRoute: OnboardingProfileSetupIndexRoute,
  }

const OnboardingProfileSetupRouteWithChildren =
  OnboardingProfileSetupRoute._addFileChildren(
    OnboardingProfileSetupRouteChildren,
  )

interface OnboardingRouteChildren {
  OnboardingProfileSetupRoute: typeof OnboardingProfileSetupRouteWithChildren
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProfileSetupRoute: OnboardingProfileSetupRouteWithChildren,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SponsorRouteChildren {
  SponsorCreateIndexRoute: typeof SponsorCreateIndexRoute
  SponsorScholarsIndexRoute: typeof SponsorScholarsIndexRoute
  SponsorScholarshipsIndexRoute: typeof SponsorScholarshipsIndexRoute
  SponsorScholarshipIdApplicantsRoute: typeof SponsorScholarshipIdApplicantsRoute
  SponsorProfileSponsorSponsorIdIndexRoute: typeof SponsorProfileSponsorSponsorIdIndexRoute
  SponsorScholarshipIdEditIndexRoute: typeof SponsorScholarshipIdEditIndexRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorCreateIndexRoute: SponsorCreateIndexRoute,
  SponsorScholarsIndexRoute: SponsorScholarsIndexRoute,
  SponsorScholarshipsIndexRoute: SponsorScholarshipsIndexRoute,
  SponsorScholarshipIdApplicantsRoute: SponsorScholarshipIdApplicantsRoute,
  SponsorProfileSponsorSponsorIdIndexRoute:
    SponsorProfileSponsorSponsorIdIndexRoute,
  SponsorScholarshipIdEditIndexRoute: SponsorScholarshipIdEditIndexRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

interface StudentRouteChildren {
  StudentDisbursementsIndexRoute: typeof StudentDisbursementsIndexRoute
  StudentDiscoverIndexRoute: typeof StudentDiscoverIndexRoute
  StudentHomeIndexRoute: typeof StudentHomeIndexRoute
  StudentProfileStudentStudentIdIndexRoute: typeof StudentProfileStudentStudentIdIndexRoute
  StudentScholarshipIdApplyIndexRoute: typeof StudentScholarshipIdApplyIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDisbursementsIndexRoute: StudentDisbursementsIndexRoute,
  StudentDiscoverIndexRoute: StudentDiscoverIndexRoute,
  StudentHomeIndexRoute: StudentHomeIndexRoute,
  StudentProfileStudentStudentIdIndexRoute:
    StudentProfileStudentStudentIdIndexRoute,
  StudentScholarshipIdApplyIndexRoute: StudentScholarshipIdApplyIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _404Route: _404Route,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SponsorRoute: SponsorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  VerificationCallbackRoute: VerificationCallbackRoute,
  LandingAboutIndexRoute: LandingAboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
